# Generated by Django 6.0.3 on 2026-04-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_purchase_price_alter_product_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('CANNED', 'Canned Goods'), ('FROZEN', 'Frozen Goods'), ('CLOTHES', 'Clothes'), ('SCHOOL', 'School Supplies'), ('HARDWARE', 'Hardware Stuffs'), ('BEVERAGES', 'Beverages'), ('SNACKS', 'Snacks'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
