# Generated by Django 6.0.4 on 2026-05-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_product_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('CANNED', 'Canned Goods'), ('FROZEN', 'Frozen Goods'), ('CLOTHES', 'Clothes'), ('SCHOOL', 'School Supplies'), ('HARDWARE', 'Hardware Supplies'), ('SOAPS', 'Laundry and Bath Care'), ('WOMENCARE', 'Feminine Care'), ('CLEANING', 'Household Cleaning Supplies'), ('BEVERAGES', 'Beverages'), ('SNACKS', 'Snacks'), ('NOODLES', 'Noodles'), ('COFFEE', 'Packaged Coffee'), ('JUICE', 'Packaged Juice'), ('ELECTRONICS', 'Electronics'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
