# Generated by Django 6.0.4 on 2026-05-05 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='branch',
            field=models.CharField(choices=[('main', 'Main Branch'), ('branch1', 'Branch 1'), ('branch2', 'Branch 2'), ('branch3', 'Branch 3'), ('branch4', 'Branch 4')], default='main', max_length=10),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dark_mode', models.BooleanField(default=False)),
                ('primary_color', models.CharField(choices=[('pink', 'Pink'), ('blue', 'Blue'), ('green', 'Green'), ('purple', 'Purple'), ('orange', 'Orange'), ('red', 'Red'), ('teal', 'Teal'), ('indigo', 'Indigo')], default='pink', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
