# Generated by Codex on 2026-05-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_userregistration_branch_userregistration_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='staff_role',
            field=models.CharField(
                choices=[('cashier', 'Cashier'), ('inventory', 'Inventory Staff')],
                default='cashier',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='staff_role',
            field=models.CharField(
                choices=[('cashier', 'Cashier'), ('inventory', 'Inventory Staff')],
                default='cashier',
                max_length=20,
            ),
        ),
    ]
